######################################################################
# Automatically generated by qmake (3.1) Sun Jun 28 20:33:49 2020
######################################################################

QMAKE_CXXFLAGS += -std=c++17 -g
QT += widgets core script
TEMPLATE = app
LIBS += -lgtest -lpthread
TARGET = Elegant86
INCLUDEPATH += . ..
RESOURCES = ../resources.qrc

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += ../mainwindow.h \
           ../codeEditor/codeeditor.h \
           ../codeEditor/highliter.h \
           ../codeEditor/linenumber.h \
           ../assembler/base.h \
           ../assembler/precom.h \
           ../assembler/mov.h \
           ../Editor.h \
           ../Simulate.h \
           ../console.h \
           ../utils.h \
           ../variables.h \
           ../ports.h \
           ../stack.h \
           ../assembler/fpasm/fpasm.h \
           ../assembler/add.h

SOURCES += main.cpp \
           ../mainwindow.cpp \
           ../codeEditor/codeeditor.cpp \
           ../codeEditor/highliter.cpp \
           ../codeEditor/linenumber.cpp \
           ../assembler/base.cpp \
           ../assembler/mov.cpp \
           ../Editor.cpp \
           ../Simulate.cpp \
           ../actions.cpp \
           ../console.cpp \
           ../regsView.cpp \
           ../utils.cpp \
           ../variables.cpp \
           ../ports.cpp \
           ../stack.cpp \
           ../assembler/fpasm/fpasm.cpp \
           ../assembler/add.cpp \
           add.hpp \
           mov.hpp \
